[package]
name = "nkinematics-urdf"
version = "0.1.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]

[dependencies]
nkinematics = { path = "../nkinematics" }
urdf-rs = { path = "../urdf-rs" }
nalgebra = "0.11.0"
alga = "0.5.1"