[package]
name = "rrt-planner"
version = "0.1.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]

[dependencies]
kdtree = "*"
rand = "*"
log = "*"
env_logger = "*"
clippy = { version = "*", optional = true }

[features]
default = []
