[package]
name = "k"
version = "0.1.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]

[dependencies]
nalgebra = "0.11.0"
alga = "0.5.1"
urdf-rs = "0.1.5"
log = "0.3"

[dev-dependencies]
kiss3d = "0.8.0"
glfw = "0.8.0" # required by kiss3d
