[package]
name = "k"
version = "0.1.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]

[dependencies]
nalgebra = "0.11.0"
alga = "0.5.1"

[lib]
name = "k"
path = "src/lib.rs"

[dev-dependencies]
kiss3d = "0.8.0"
glfw = "0.8.0" # required by kiss3d
