[package]
name = "k-urdf"
version = "0.1.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]

[dependencies]
k = { version = "0.1.0", path = ".." }
urdf-rs = "0.1.5"
nalgebra = "0.11.0"
alga = "0.5.1"
log = "0.3"
